services:
  gogs_main_restore:
    image: kellyalsa/gogs:0.12.3
    working_dir: /app
    entrypoint: tail -f /dev/null
    volumes:
      - ./instances/main:/app
      - /pan_data/Upload/gogs_backup/main:/backup

  gogs_external_restore:
    image: kellyalsa/gogs:0.12.3
    working_dir: /app
    entrypoint: tail -f /dev/null
    volumes:
      - ./instances/external:/app
      - /pan_data/Upload/gogs_backup/external:/backup

  gogs_main:
    image: gogs/gogs:0.12.3
    working_dir: /app
    volumes:
      - ./gogs_instances/main:/data
    environment:
      TZ: Asia/Shanghai
    ports:
      - "3004:3000"
      - "10022:22"

  gogs_external:
    image: gogs/gogs:0.12.3
    working_dir: /app
    volumes:
      - ./gogs_instances/external:/data
    environment:
      TZ: Asia/Shanghai
    ports:
      - "3005:3000"
      - "10023:22"

  gogs_main_db:
    image: mariadb:10.3.34
    environment:
      - MARIADB_ROOT_PASSWORD=12345678
      - MARIADB_DATABASE=gogs_main
    volumes:
      - ./instances/main/database:/var/lib/mysql:Z
    ports:
      - "20305:3306"

  gogs_external_db:
    image: mariadb:10.3.34
    environment:
      - MARIADB_ROOT_PASSWORD=12345678
      - MARIADB_DATABASE=gogs_external
    volumes:
      - ./instances/external/database:/var/lib/mysql:Z
    ports:
      - "20306:3306"
